### ISSUE TITLE
Bundled Javascript module errors due to strict mode

### ISSUE THREAD

**Issue by torgabor** [Elringus/DotNetJS#80]
Hi!

I found that after bundling, the created module does not work (`dotnet.boot()` crashes). This is due to the usage of undeclared identifiers assigned in certain functions. This shouldn't be a problem, but since some bundlers seem to tack on `'use strict';` where they shouldn't, it becomes an issue, and fixing it shouldn't cause any problems.

The offending functions are:

`_js_to_mono_obj` : `result` is undeclared
`bind_method` : `bodyJs` is underclared
`_handle_exception_and_produce_result_for_call` : `result` is undeclared

**Comment by Elringus** [comment]
Hi, Those come from .NET runtime's auto-generated JS wrapper. We currently have to use a modified version of 6.0 runtime (due to #20) and are patching the wrapper to resolve some critical issues, but otherwise I'd like to refrain from patching it further, as there are plans to drop the modified runtime as soon as those critical issues are resolved (hopefully in .NET 7.0 or 8.0).

The strict violations in the wrapper will hopefully be also resolved at that point (or maybe they already are).

**Comment by torgabor** [comment]
Thanks, but this is kind of a deal-breaker for us - we are using DotNetJS right now. 
Do you have a workaround in mind?
I mean, this is your library, and your call, but I feel like fixing this bug wouldn't have any negative impacts.
Down the road, there should be a proper fix for this.

**Comment by Elringus** [comment]
For a temporary workaround (until we migrate to the next .NET runtime), I'd suggest using bundlers that can work with this. For example, I'm using webpack in various scenarios (node, webworker extension for vscode, react) and do not encounter any issues.

If you still want to patch the wrapper check out https://github.com/Elringus/DotNetJS/blob/8dee89d997da1158c1ea6830435a1dabc6608924/JavaScript/scripts/compile-runtime.sh#L13 for a reference.

**Comment by torgabor** [comment]
Thanks I'll look into that.
I did a PR if you decide to change your mind.

(https://github.com/Elringus/DotNetJS/pull/81)

**Comment by torgabor** [comment]
Created a new PR with your feedback

(https://github.com/Elringus/DotNetJS/pull/82)
